/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaPrincipal;

import configuracion.fondoPantalla;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import vista.Caja.frmiCierreCaja;
import vista.Caja.frmiCobrar;
import vista.Clientes.frmiCatalogo;
import vista.Productos.frmiCatalogoProducto;
import vista.Proveedores.frmiCatalogoPv;
import vista.Ventas.frmiCatalogoVentas;

/**
 *
 * @author Joel
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        setTitle("SoftSystem 1.0.0");
        SplashScreen.iconoBarra(this);
        this.setExtendedState(MAXIMIZED_BOTH);
        escritorio.setBorder(new fondoPantalla());
        
    }

    public void centrarVentana(JInternalFrame ventana){
        int x = (escritorio.getWidth()/2)-(ventana.getWidth()/2);
        int y = (escritorio.getHeight()/2) - (ventana.getHeight()/2);
        
        if (ventana.isShowing()) {
            ventana.setLocation(x, y);
            ventana.toFront();
        } else {
            escritorio.add(ventana);
            ventana.setLocation(x, y);
          //  escritorio.setSelectedFrame(ventana);//establece activo el jinternaFrame o establece el foco de atencion
           
            ventana.setVisible(true);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    frmiCatalogo catalogo;
    frmiCatalogoPv catalogoProv;
    frmiCatalogoProducto productos;
    frmiCobrar cobrar;
    frmiCatalogoVentas ventas;
    vista.Usuario.frmiCatalogo usuarios;
    frmiCierreCaja caja;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        lbl_Usuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn_usuario = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        mn_cliente = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        mn_proveedor = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        mn_producto = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        mn_venta = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mni_acercaSoft = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(58, 57, 57));
        jPanel2.setForeground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Usuario.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbl_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuario.setText("USUARIO");
        jPanel2.add(lbl_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        escritorio.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 236, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(escritorio, java.awt.BorderLayout.CENTER);

        mn_usuario.setText("Usuarios");
        mn_usuario.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        mn_usuario.setPreferredSize(new java.awt.Dimension(77, 30));
        mn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_usuarioActionPerformed(evt);
            }
        });

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem10.setText("Ver");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mn_usuario.add(jMenuItem10);

        jMenuBar1.add(mn_usuario);

        mn_cliente.setText("Clientes");
        mn_cliente.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem5.setText("Ver");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mn_cliente.add(jMenuItem5);

        jMenuBar1.add(mn_cliente);

        mn_proveedor.setText("Proveedores");
        mn_proveedor.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem7.setText("Ver");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mn_proveedor.add(jMenuItem7);

        jMenuBar1.add(mn_proveedor);

        mn_producto.setText("Productos");
        mn_producto.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem8.setText("Ver");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mn_producto.add(jMenuItem8);

        jMenuBar1.add(mn_producto);

        mn_venta.setText("Ventas");
        mn_venta.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem9.setText("Ver");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mn_venta.add(jMenuItem9);

        jMenuBar1.add(mn_venta);

        jMenu6.setText("Caja");
        jMenu6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setText("Cobrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setText("Cierre de caja");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Facturas");
        jMenu7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem6.setText("Ver");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Ayuda");
        jMenu8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        mni_acercaSoft.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mni_acercaSoft.setText("Acerca de SoftSystem");
        mni_acercaSoft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_acercaSoftActionPerformed(evt);
            }
        });
        jMenu8.add(mni_acercaSoft);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem4.setText("Manual de Uso");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (!(caja instanceof frmiCierreCaja)) {
            caja = new frmiCierreCaja();
        }
        centrarVentana(caja);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       if (!(catalogo instanceof frmiCatalogo)) {//si al presionar no hay instancia entoces que me agregue la inst
            catalogo = new frmiCatalogo();   //instancear solo si no hay una
            
        }
        centrarVentana(catalogo); // si ya existe una instancea solo que me centre
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if(!(catalogoProv instanceof frmiCatalogoPv)){
           catalogoProv = new frmiCatalogoPv();
           
        }
        centrarVentana(catalogoProv);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (!(productos instanceof frmiCatalogoProducto)) {
            productos = new frmiCatalogoProducto();
        }
        centrarVentana(productos);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (!(cobrar instanceof frmiCobrar)) {
            cobrar = new frmiCobrar();
        }
        centrarVentana(cobrar);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (!(ventas instanceof frmiCatalogoVentas)) {
            ventas = new frmiCatalogoVentas();
        }
        centrarVentana(ventas);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if(!(usuarios instanceof vista.Usuario.frmiCatalogo)){
           usuarios = new vista.Usuario.frmiCatalogo();
       }
        centrarVentana(usuarios);
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    
    private void mn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_usuarioActionPerformed
       
    }//GEN-LAST:event_mn_usuarioActionPerformed

    private void mni_acercaSoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_acercaSoftActionPerformed
        JOptionPane.showMessageDialog(this, "Somos una empresa de Desarrollo de Software  multiplataforma \n"
                                            + "fundada en el año 2020. El objetivo  de la empresa es crear\n"
                                            + "sistemas de calidad que resuelvan  todo tipo  de  problemas\n "
                                            + "y   así   satisfacer   las    necesisdades   del   usuario.\n"
                                            + "Creamos todo tipo de aplicaciones  ya sean  de  escritorio,\n"
                                            + "móviles y web. Puedes acceder a nuestros servicios en línea\n"
                                            + "en   www.corporacionsofsystem.com.ec    o     comunicate al\n"
                                            + "0999124372   desarrollador  de   sofware  Joel  Echeverría.\n"
                                            ,"Acerca de SoftSystem",0,new ImageIcon(getClass().getResource("/imagenes/micorporacion.png")));
    }//GEN-LAST:event_mni_acercaSoftActionPerformed

    Manual manual;
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (!(manual instanceof Manual)) {
            manual = new Manual(); 
        }
        centrarVentana(manual);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JOptionPane.showMessageDialog(null,"Facturación proximamente en la version 2.0.0");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lbl_Usuario;
    public static javax.swing.JMenu mn_cliente;
    public static javax.swing.JMenu mn_producto;
    public static javax.swing.JMenu mn_proveedor;
    public static javax.swing.JMenu mn_usuario;
    public static javax.swing.JMenu mn_venta;
    private javax.swing.JMenuItem mni_acercaSoft;
    // End of variables declaration//GEN-END:variables
}
