/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaPrincipal;

import com.sun.awt.AWTUtilities;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
         AWTUtilities.setWindowOpaque(this, false);
         this.setLocationRelativeTo(null);
         iconoBarra(this);
         splash.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         progreso.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
         correr();
         
    }
    
    public static void iconoBarra(JFrame frame){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icoviveres.png"));
       
        frame.setIconImage(icono);
    }
    void correr(){
        Thread th = new Thread(new Runnable() {
            @Override
            public void run() {
                inicio.setText("Iniciando módulos.....");
                progreso.setValue(10);
                parar();
                inicio.setText("Cargando la base de datos.....");
                progreso.setValue(30);
                parar();
                inicio.setText("Cargando interfaz.....");
                progreso.setValue(50);
                parar();
                progreso.setValue(70);
                parar();
                progreso.setValue(100);
                inicio.setText("Terminando carga.....");
                parar();
                dispose();
                frmLogin login = new frmLogin();
                login.setVisible(true);
            }
            
        });
        th.start();
         
    }
    void parar(){
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JLabel();
        progreso = new javax.swing.JProgressBar();
        splash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setText("inicio");
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        progreso.setBackground(new java.awt.Color(255, 255, 255));
        progreso.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 304, 430, 20));

        splash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/splash.png"))); // NOI18N
        getContentPane().add(splash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 452));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inicio;
    private javax.swing.JProgressBar progreso;
    private javax.swing.JLabel splash;
    // End of variables declaration//GEN-END:variables
}
