/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import configuracion.BD;
import configuracion.estiloHeader;
import configuracion.estiloTabla;
import controlador.cajaCont;
import controlador.clientesCont;
import controlador.detalleVentasCont;
import controlador.productosCont;
import controlador.ventasCont;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.cajaModel;
import modelo.clientesModel;
import vista.Productos.frmiCatalogoProducto;
import vista.Ventas.frmiCatalogoVentas;
import vistaPrincipal.frmMenu;

/**
 *
 * @author user
 */
public class frmiSelectClie extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmiSelectClie
     */
    public frmiSelectClie() {
        initComponents();
        buscar("");
        table_clientes.setDefaultRenderer(Object.class, new estiloTabla());
        table_clientes.getTableHeader().setDefaultRenderer(new estiloHeader());
        this.setTitle("SELECCIONAR CLIENTE");
    }

    public void centrarVentana(JInternalFrame ventana) {
        int x = (vistaPrincipal.frmMenu.escritorio.getWidth() / 2) - (ventana.getWidth() / 2);
        int y = (vistaPrincipal.frmMenu.escritorio.getHeight() / 2) - (ventana.getHeight() / 2);

        if (ventana.isVisible()) {
            ventana.setLocation(x, y);
            ventana.toFront();
        } else {
            frmMenu.escritorio.add(ventana);
            ventana.setLocation(x, y);
            ventana.setVisible(true);
        }

    }

    public static void buscar(String Busca) {
        Statement st;
        ResultSet rs;

        DefaultTableModel modelo = (DefaultTableModel) frmiSelectClie.table_clientes.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        String sql;

        if (Busca.isEmpty()) {
            sql = clientesModel.leer;
        } else {
            sql = "SELECT * FROM CLIENTES WHERE NOMCLIE LIKE '%" + Busca + "%' or CEDCLIE LIKE '%" + Busca + "%' ORDER BY NOMCLIE";
        }

        String[] datos = new String[5];

        try {
            st = BD.conexion().createStatement();
            rs = st.executeQuery(sql);

            while (rs.next()) {
                datos[0] = rs.getString("CODCLIE");
                datos[1] = rs.getString("CEDCLIE");
                datos[2] = rs.getString("NOMCLIE");
                datos[3] = rs.getString("DIRECCLIE");
                datos[4] = rs.getString("TELEFCLIE");

                modelo.addRow(datos);

            }

        } catch (SQLException ex) {
            Logger.getLogger(clientesCont.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void enviarDatos() {
        int fila = table_clientes.getSelectedRow();
        String nombreClie = table_clientes.getValueAt(fila, 2).toString();

        String nVenta = frmiCobrar.lbl_NumeroVenta.getText();
        String vendedor = frmMenu.lbl_Usuario.getText();
        String fecha = frmiCobrar.lbl_InsertarFecha.getText();
        String total = frmiCobrar.txt_Total.getText();

        DefaultTableModel modelo = (DefaultTableModel) frmiCatalogoVentas.table.getModel();

        String[] dato = new String[5];

        dato[0] = nVenta;
        dato[1] = nombreClie;
        dato[2] = vendedor;
        dato[3] = fecha;
        dato[4] = total;
        modelo.addRow(dato);
    }

    //algoritmo para recolectar todos los productos ingresados
    public static String cod;
    public static String cantidad;

    detalleVentasCont dvc = new detalleVentasCont();
    productosCont prodCont = new productosCont();

    public void productosVender() {
        for (int i = 0; i < frmiCobrar.table.getRowCount(); i++) {
            cod = frmiCobrar.table.getValueAt(i, 0).toString();
            cantidad = frmiCobrar.table.getValueAt(i, 4).toString();
            prodCont.actualizarStockcc();
            dvc.guardar();

        }

    }
    vista.Clientes.frmiNuevo nuevoCliente;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_clientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Buscar = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_Salir = new javax.swing.JButton();
        btn_AniadirClie = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cédula", "Nombre-Apellido", "Dirección", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_clientes.getTableHeader().setReorderingAllowed(false);
        table_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_clientes);
        if (table_clientes.getColumnModel().getColumnCount() > 0) {
            table_clientes.getColumnModel().getColumn(1).setPreferredWidth(150);
            table_clientes.getColumnModel().getColumn(2).setPreferredWidth(200);
            table_clientes.getColumnModel().getColumn(3).setPreferredWidth(250);
            table_clientes.getColumnModel().getColumn(4).setPreferredWidth(120);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setText("Buscar");

        txt_Buscar.setBackground(new java.awt.Color(204, 204, 255));
        txt_Buscar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        txt_Buscar.setPlaceholder("Nombre y Apellido");
        txt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarActionPerformed(evt);
            }
        });
        txt_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_Salir.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Salir.setText("Cancelar");
        btn_Salir.setPreferredSize(new java.awt.Dimension(105, 29));
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        btn_AniadirClie.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_AniadirClie.setText("+Add Cliente");
        btn_AniadirClie.setPreferredSize(new java.awt.Dimension(125, 29));
        btn_AniadirClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AniadirClieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 147, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AniadirClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)
                        .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AniadirClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AniadirClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AniadirClieActionPerformed
        if (!(nuevoCliente instanceof vista.Clientes.frmiNuevo)) {
            nuevoCliente = new vista.Clientes.frmiNuevo();
        }
        centrarVentana(nuevoCliente);
    }//GEN-LAST:event_btn_AniadirClieActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.doDefaultCloseAction();

    }//GEN-LAST:event_btn_SalirActionPerformed
    cajaCont productos = new cajaCont();
    private void table_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clientesMouseClicked

        frmiCobrar.siCliente = true;

        ventasCont ventas = new ventasCont();
        ventas.guardar();

        productosVender();
        cajaModel.codigoVent();

        DefaultTableModel model = (DefaultTableModel) frmiCobrar.table.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        frmiCobrar.txt_Total.setText("");
        try {
            dvc.buscar("");

        } catch (Exception e) {
        }

        productos.buscar("");

        try {
            prodCont.buscar("");
            frmiCatalogoProducto.giveFormat();
        } catch (Exception e) {

        }

        try {
            frmiCierreCaja.ejecutar();
        } catch (Exception e) {
        }
        this.doDefaultCloseAction();
    }//GEN-LAST:event_table_clientesMouseClicked

    private void txt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarActionPerformed

    private void txt_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarKeyReleased
        buscar(txt_Buscar.getText());
        txt_Buscar.setText(txt_Buscar.getText().toUpperCase());
    }//GEN-LAST:event_txt_BuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AniadirClie;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable table_clientes;
    private app.bolivia.swing.JCTextField txt_Buscar;
    // End of variables declaration//GEN-END:variables
}
