/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Ventas;

import configuracion.BD;
import configuracion.estiloHeader;
import configuracion.estiloTabla;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class listaProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmi_nota
     */
    public listaProductos() {
        initComponents();
        this.setTitle("LISTA DE PRODUCTOS VENDIDOS");
        tableVerProducto.setDefaultRenderer(Object.class, new estiloTabla());
        tableVerProducto.getTableHeader().setDefaultRenderer(new estiloHeader());
    }
    
    
    
    
    
   
    
    public static void verProducto(String nVenta){
        String sql = "SELECT DESCRIPCION,CANTIDAD FROM DETALLE_VENTAS INNER JOIN PRODUCTOS ON DETALLE_VENTAS.CODPROD = PRODUCTOS.CODPROD WHERE NUMVENT ='"+nVenta+"'";
        String[] list = new String[2];
        DefaultTableModel modelo = (DefaultTableModel) tableVerProducto.getModel();
        //DefaultListModel modelo = new DefaultListModel();
        
        while(modelo.getRowCount() >0){
            modelo.removeRow(0);
        }
        
        //ArrayList lista = new ArrayList();
        
        try {
            Statement st = BD.conexion().createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            
            while (rs.next()) {                
               // lista.add(rs.getString("DESCRIPCION"));
                //modelo.removeAllElements();
                
                list[0] = rs.getString("DESCRIPCION");
                list[1] = rs.getString("CANTIDAD");
                
                modelo.addRow(list);
            }
                
//            for (int i = 0; i < lista.size(); i++) {
//                modelo.addElement(lista.get(i));
//            }
            //lsListaProdutos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(listaProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVerProducto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        tableVerProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTO", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableVerProducto);
        if (tableVerProducto.getColumnModel().getColumnCount() > 0) {
            tableVerProducto.getColumnModel().getColumn(0).setResizable(false);
            tableVerProducto.getColumnModel().getColumn(0).setPreferredWidth(150);
            tableVerProducto.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );

        btnCerrar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setPreferredSize(new java.awt.Dimension(105, 27));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tableVerProducto;
    // End of variables declaration//GEN-END:variables
}
