/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Proveedores;

import configuracion.estiloHeader;
import configuracion.estiloTabla;
import controlador.proveedoresCont;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.proveedoresModel;
import vistaPrincipal.frmMenu;

/**
 *
 * @author user
 */
public class frmiCatalogoPv extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmiCatalogo
     */
    proveedoresCont proveedores = new proveedoresCont();
    frmiActualizarPv actualizar;

    public frmiCatalogoPv() {
        initComponents();
        this.setTitle("CATALOGO DE PROVEEDORES");
        tableProv.getTableHeader().setDefaultRenderer(new estiloHeader());
        tableProv.setDefaultRenderer(Object.class, new estiloTabla());
        proveedores.buscar("");
        tableProv.setCursor(new Cursor(12));
        this.setSize(888, 350);
        tableProv.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        insertaricono();
    }

    void insertaricono() {
        this.setFrameIcon(new ImageIcon(getClass().getResource("/imagenes/catalogoicon.png")));
    }

    public void centrar(JInternalFrame ventana) {
        int x = (frmMenu.escritorio.getWidth() / 2) - (ventana.getWidth() / 2);
        int y = (frmMenu.escritorio.getHeight() / 2) - (ventana.getHeight() / 2);

        if (ventana.isVisible()) {
            ventana.setLocation(x, y);
            ventana.toFront();
        } else {
            frmMenu.escritorio.add(ventana);
            ventana.setVisible(true);
            ventana.setLocation(x, y);

        }
    }

    public static void seleccionarFila(String idPv) {

        for (int i = 0; i < tableProv.getRowCount(); i++) {
            if (idPv.equals(tableProv.getValueAt(i, 0))) {
                tableProv.setRowSelectionInterval(i, i);
            }
        }
    }

    public void borrarSeleccion() {
        int fila = frmiCatalogoPv.tableProv.getSelectedRow();
        if (frmiCatalogoPv.tableProv.getSelectedRow() > -1) {
            frmiCatalogoPv.tableProv.removeRowSelectionInterval(fila, fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProv = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_BuscarProv = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_Nuevo = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(894, 356));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cédula", "Nombre-Apellido", "Dirección", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProv.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableProv);
        if (tableProv.getColumnModel().getColumnCount() > 0) {
            tableProv.getColumnModel().getColumn(0).setResizable(false);
            tableProv.getColumnModel().getColumn(1).setResizable(false);
            tableProv.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableProv.getColumnModel().getColumn(2).setResizable(false);
            tableProv.getColumnModel().getColumn(2).setPreferredWidth(200);
            tableProv.getColumnModel().getColumn(3).setResizable(false);
            tableProv.getColumnModel().getColumn(3).setPreferredWidth(250);
            tableProv.getColumnModel().getColumn(4).setResizable(false);
            tableProv.getColumnModel().getColumn(4).setPreferredWidth(120);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel1.setText("Buscar");

        txt_BuscarProv.setBackground(new java.awt.Color(204, 204, 255));
        txt_BuscarProv.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        txt_BuscarProv.setPlaceholder("Nombre y Apellido");
        txt_BuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarProvActionPerformed(evt);
            }
        });
        txt_BuscarProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BuscarProvKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_BuscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_BuscarProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_Nuevo.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.setPreferredSize(new java.awt.Dimension(105, 27));
        btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Nuevo);

        btn_Eliminar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setPreferredSize(new java.awt.Dimension(105, 27));
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Eliminar);

        btn_Actualizar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.setPreferredSize(new java.awt.Dimension(105, 29));
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Actualizar);

        btn_Salir.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 328, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)
                        .addComponent(btn_Salir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btn_Salir)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    frmiNuevoPv nuevo;
    private void btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoActionPerformed
        if (!(nuevo instanceof frmiNuevoPv)) {
            nuevo = new frmiNuevoPv();

        }
        centrar(nuevo);
        borrarSeleccion();
    }//GEN-LAST:event_btn_NuevoActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.doDefaultCloseAction();
        borrarSeleccion();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        if (tableProv.getSelectedRow() > -1) {
            if (!(actualizar instanceof frmiActualizarPv)) {
                actualizar = new frmiActualizarPv();
                actualizar.cargarDatos();

            }
            actualizar.enviarRegistro();
            centrar(actualizar);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_ActualizarActionPerformed

    public static String codigo;
    public static String nombre;
    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed

        if (tableProv.getSelectedRow() > -1) {
            int fila = tableProv.getSelectedRow();
            codigo = tableProv.getValueAt(fila, 0).toString();
            nombre = tableProv.getValueAt(fila, 2).toString();
            int op = JOptionPane.showConfirmDialog(null, "Está seguro que quiere eliminar a: " + nombre, "Eliminar", JOptionPane.OK_OPTION);
            if (op == JOptionPane.OK_OPTION) {

                proveedores.eliminar();
                proveedores.buscar("");
                proveedoresModel.generarCodigo();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void txt_BuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarProvActionPerformed

    private void txt_BuscarProvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BuscarProvKeyReleased
        proveedores.buscar(txt_BuscarProv.getText());
        txt_BuscarProv.setText(txt_BuscarProv.getText().toUpperCase());

    }//GEN-LAST:event_txt_BuscarProvKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tableProv;
    private app.bolivia.swing.JCTextField txt_BuscarProv;
    // End of variables declaration//GEN-END:variables
}
