/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Productos;

import controlador.categoriaCont;
import controlador.productosCont;
import controlador.proveedoresCont;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import modelo.productosModel;
import static vistaPrincipal.frmMenu.escritorio;

/**
 *
 * @author user
 */
public class frmiNuevoProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmi_Nuevo
     */
    proveedoresCont proveedor = new proveedoresCont();
    productosCont productos;

    public frmiNuevoProductos() {
        initComponents();
        this.setTitle("REGISTRAR PRODUCTO");
        limpiar();
        this.setFrameIcon(new ImageIcon(getClass().getResource("/imagenes/productoicon.png")));
        
    }
    public void limpiar(){
        txt_CodigoPro.setText("");
        txt_Marca.setText("");
        txt_NombrePro.setText("");
        txt_PrecioCompra.setText("");
        txt_PrecioVenta.setText("");
        txt_Stock.setText("");
        productosModel.idProductos();
        cbo_TipoCategoria.removeAllItems();
        cbo_TipoProveedor.removeAllItems();
        proveedor.ListaProv(cbo_TipoProveedor);
        categoriaCont.laCategoria(cbo_TipoCategoria);
    }
    

    public void centrar(JInternalFrame ventana) {
        int x = (escritorio.getWidth() / 2) - (ventana.getWidth() / 2);
        int y = (escritorio.getHeight() / 2) - (ventana.getHeight() / 2);

        if (ventana.isVisible()) {
            ventana.setLocation(x, y);
            ventana.toFront();
        } else {
            escritorio.add(ventana);
            ventana.setVisible(true);
            ventana.setLocation(x, y);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    frmiCategoria catego = new frmiCategoria();

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_CodigoPro = new javax.swing.JTextField();
        txt_NombrePro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbo_TipoProveedor = new javax.swing.JComboBox<>();
        txt_Marca = new javax.swing.JTextField();
        txt_PrecioCompra = new javax.swing.JTextField();
        txt_PrecioVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Stock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbo_TipoCategoria = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setText("Código Producto:");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setText("Precio Compra:");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel6.setText("Precio Venta:");

        txt_CodigoPro.setEditable(false);
        txt_CodigoPro.setBackground(new java.awt.Color(0, 0, 0));
        txt_CodigoPro.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_CodigoPro.setForeground(new java.awt.Color(255, 255, 255));

        txt_NombrePro.setBackground(new java.awt.Color(255, 255, 204));
        txt_NombrePro.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_NombrePro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NombreProKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setText("Elegir Proveedor:");

        cbo_TipoProveedor.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        txt_Marca.setBackground(new java.awt.Color(255, 255, 204));
        txt_Marca.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MarcaKeyReleased(evt);
            }
        });

        txt_PrecioCompra.setBackground(new java.awt.Color(255, 255, 204));
        txt_PrecioCompra.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_PrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PrecioCompraKeyTyped(evt);
            }
        });

        txt_PrecioVenta.setBackground(new java.awt.Color(255, 255, 204));
        txt_PrecioVenta.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_PrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PrecioVentaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("Stock:");

        txt_Stock.setBackground(new java.awt.Color(255, 255, 204));
        txt_Stock.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_Stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_StockKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel9.setText("Elegir Categoría:");

        cbo_TipoCategoria.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        cbo_TipoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_TipoCategoriaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jButton1.setText("Nueva Categoría");
        jButton1.setPreferredSize(new java.awt.Dimension(147, 29));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        btn_Guardar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Guardar.setText("Guardar");
        btn_Guardar.setPreferredSize(new java.awt.Dimension(89, 29));
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Guardar);

        btn_Salir.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.setPreferredSize(new java.awt.Dimension(65, 29));
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Salir);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_NombrePro, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                            .addComponent(txt_PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbo_TipoProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(47, 47, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))))
                                .addGap(18, 24, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_TipoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(txt_CodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_CodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbo_TipoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbo_TipoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 34, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/produtos.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
          
            
        if (txt_Marca.getText().equals("") || txt_NombrePro.getText().equals("") || txt_PrecioCompra.getText().equals("")
                || txt_PrecioVenta.getText().equals("") || txt_Stock.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Es obligatorio llenar todos los campos", "Error",
                     JOptionPane.ERROR_MESSAGE);
        } else if (cbo_TipoCategoria.getSelectedIndex() == 0 || cbo_TipoProveedor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Es obligatorio llenar todos los campos", "Error",
                     JOptionPane.ERROR_MESSAGE);
        } else {
            
            String idCategoria = cbo_TipoCategoria.getItemAt(cbo_TipoCategoria.getSelectedIndex()).getIdCategoria();
            String proveedorCod = cbo_TipoProveedor.getItemAt(cbo_TipoProveedor.getSelectedIndex()).getCodigo();
            Float compra = Float.parseFloat((txt_PrecioCompra.getText()).replaceAll("[^0-9]", "."));
            float venta = Float.parseFloat(txt_PrecioVenta.getText().replaceAll("[^0-9]", "."));
            int stock = Integer.parseInt(txt_Stock.getText());
            productos = new productosCont(txt_CodigoPro.getText(), idCategoria, proveedorCod,
                    txt_NombrePro.getText(), txt_Marca.getText(), compra, venta, stock);
            productos.guardar();
            String id = txt_CodigoPro.getText();
            productos.buscar("");
            frmiCatalogoProducto.seleccionar(id);
            limpiar();
        }
        frmiCatalogoProducto.giveFormat();

    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.doDefaultCloseAction();
        limpiar();
        //this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void cbo_TipoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_TipoCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_TipoCategoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!(catego instanceof frmiCategoria)) {
            catego = new frmiCategoria();
        }
        centrar(catego);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_PrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PrecioCompraKeyTyped
        char letra = evt.getKeyChar();
        
        if (letra >='a' || letra>='A') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_PrecioCompraKeyTyped

    private void txt_StockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_StockKeyTyped
        char letra = evt.getKeyChar();
        if (letra >='a'||letra>='A') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_StockKeyTyped

    private void txt_PrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PrecioVentaKeyTyped
        char letra = evt.getKeyChar();
        if (letra >='a'||letra>='A') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_PrecioVentaKeyTyped

    private void txt_NombreProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreProKeyReleased
         txt_NombrePro.setText(txt_NombrePro.getText().toUpperCase());
    }//GEN-LAST:event_txt_NombreProKeyReleased

    private void txt_MarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MarcaKeyReleased
        txt_Marca.setText(txt_Marca.getText().toUpperCase());
    }//GEN-LAST:event_txt_MarcaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Salir;
    public static javax.swing.JComboBox<controlador.categoriaCont> cbo_TipoCategoria;
    private javax.swing.JComboBox<proveedoresCont> cbo_TipoProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txt_CodigoPro;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JTextField txt_NombrePro;
    private javax.swing.JTextField txt_PrecioCompra;
    private javax.swing.JTextField txt_PrecioVenta;
    private javax.swing.JTextField txt_Stock;
    // End of variables declaration//GEN-END:variables
}
