/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Productos;

import controlador.cajaCont;
import controlador.categoriaCont;
import controlador.productosCont;
import controlador.proveedoresCont;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import vista.Caja.frmiElegirProd;
import static vista.Productos.frmiCatalogoProducto.table_Producto;

/**
 *
 * @author user
 */
public class frmiActualizarProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmi_Nuevo
     */
    proveedoresCont proveedor = new proveedoresCont();
    productosCont p = new productosCont();

    public frmiActualizarProductos() {
        initComponents();
        this.setTitle("ACTUALIZAR PRODUCTO");
        this.setFrameIcon(new ImageIcon(getClass().getResource("/imagenes/actualizarpers.png")));
        proveedor.ListaProv(cbo_TipoProveedor);
        categoriaCont.laCategoria(cbo_TipoCategoria);

    }
    public static String cod;

    public void enviarDatos() {
        table_Producto.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
            if (table_Producto.getSelectedRow() > -1) {

                cargar();
            }
        });
    }

    public void cargar() {
        int fila = table_Producto.getSelectedRow();
        cod = table_Producto.getValueAt(fila, 0).toString();

        for (int i = 1; i < cbo_TipoCategoria.getItemCount(); i++) {

            if (p.verid().equals(cbo_TipoCategoria.getItemAt(i).getIdCategoria())) {
                cbo_TipoCategoria.setSelectedIndex(i);

                break;

            }

        }

        for (int i = 1; i < cbo_TipoProveedor.getItemCount(); i++) {
            if (p.idproveedor().equals(cbo_TipoProveedor.getItemAt(i).getCodigo())) {
                cbo_TipoProveedor.setSelectedIndex(i);

                break;
            }

        }

        txt_CodigoPro.setText(table_Producto.getValueAt(fila, 0).toString());
        txt_NombrePro.setText(table_Producto.getValueAt(fila, 1).toString());
        txt_Marca.setText(table_Producto.getValueAt(fila, 2).toString());
        txt_PrecioCompra.setText(table_Producto.getValueAt(fila, 3).toString());
        txt_PrecioVenta.setText(table_Producto.getValueAt(fila, 4).toString());
        txt_Stock.setText(table_Producto.getValueAt(fila, 5).toString());

    }

    public void seleccionar(String id) {
        for (int i = 0; i < table_Producto.getRowCount(); i++) {
            if (id.equals(table_Producto.getValueAt(i, 0))) {
                table_Producto.setRowSelectionInterval(i, i);
            }
        }
    }

    public String stock() {
        int fila = table_Producto.getSelectedRow();
        String regresar = table_Producto.getValueAt(fila, 5).toString();
        return regresar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_CodigoPro = new javax.swing.JTextField();
        txt_NombrePro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbo_TipoProveedor = new javax.swing.JComboBox<>();
        txt_Marca = new javax.swing.JTextField();
        txt_PrecioCompra = new javax.swing.JTextField();
        txt_PrecioVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Stock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbo_TipoCategoria = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btn_Actualizar = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_StockIngreso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel2.setText("Código Producto:");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel4.setText("Marca:");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setText("Precio Compra:");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel6.setText("Precio Venta:");

        txt_CodigoPro.setEditable(false);
        txt_CodigoPro.setBackground(new java.awt.Color(0, 0, 0));
        txt_CodigoPro.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_CodigoPro.setForeground(new java.awt.Color(255, 255, 255));

        txt_NombrePro.setBackground(new java.awt.Color(255, 255, 204));
        txt_NombrePro.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_NombrePro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NombreProKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel7.setText("Elegir Proveedor:");

        cbo_TipoProveedor.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        txt_Marca.setBackground(new java.awt.Color(255, 255, 204));
        txt_Marca.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MarcaKeyReleased(evt);
            }
        });

        txt_PrecioCompra.setBackground(new java.awt.Color(255, 255, 204));
        txt_PrecioCompra.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        txt_PrecioVenta.setBackground(new java.awt.Color(255, 255, 204));
        txt_PrecioVenta.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel8.setText("Stock Actual:");

        txt_Stock.setEditable(false);
        txt_Stock.setBackground(new java.awt.Color(0, 0, 0));
        txt_Stock.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_Stock.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel9.setText("Elegir Categoría:");

        cbo_TipoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_TipoCategoriaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_Actualizar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.setPreferredSize(new java.awt.Dimension(105, 29));
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Actualizar);

        btn_Cerrar.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        btn_Cerrar.setText("Cancelar");
        btn_Cerrar.setPreferredSize(new java.awt.Dimension(105, 27));
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cerrar);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel10.setText("Stock de Ingreso:");

        txt_StockIngreso.setBackground(new java.awt.Color(255, 255, 204));
        txt_StockIngreso.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        txt_StockIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_StockIngresoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_StockIngresoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("+/-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(txt_CodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(39, 39, 39))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(25, 25, 25)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbo_TipoProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(158, 158, 158))
                            .addComponent(txt_NombrePro, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Marca)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txt_StockIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel11))
                                            .addComponent(txt_PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbo_TipoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 73, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_CodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbo_TipoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cbo_TipoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_NombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txt_StockIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        if (txt_Marca.getText().equals("") || txt_NombrePro.getText().equals("") || txt_PrecioCompra.getText().equals("")
                || txt_PrecioVenta.getText().equals("") || txt_Stock.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Es obligatorio llenar todos los campos", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else if (cbo_TipoCategoria.getSelectedIndex() == 0 || cbo_TipoProveedor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Es obligatorio llenar todos los campos", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            int op = JOptionPane.showConfirmDialog(null, "Está seguro que desea Actualizar", "Opción Actualizar", JOptionPane.OK_OPTION);
            if (op == JOptionPane.OK_OPTION) {

                String categoria = cbo_TipoCategoria.getItemAt(cbo_TipoCategoria.getSelectedIndex()).getIdCategoria();

                String prove = cbo_TipoProveedor.getItemAt(cbo_TipoProveedor.getSelectedIndex()).getCodigo();

                Float pCompra = Float.parseFloat((txt_PrecioCompra.getText()).replaceAll("[^0-9]", "."));
                Float pVenta = Float.parseFloat(txt_PrecioVenta.getText().replaceAll("[^0-9]", "."));
                int stock = Integer.parseInt(txt_Stock.getText());

                p = new productosCont(txt_CodigoPro.getText(), categoria, prove, txt_NombrePro.getText(),
                        txt_Marca.getText(), pCompra, pVenta, stock);
                p.actualizar();
                txt_StockIngreso.setText("");
                String idprod = txt_CodigoPro.getText();
                p.buscar("");
                seleccionar(idprod);
                cajaCont producto = new cajaCont();
                try {
                    producto.buscar("");
                    frmiElegirProd.giveFormat();
                } catch (Exception e) {
                }

            }
            frmiCatalogoProducto.giveFormat();
            int fila = frmiCatalogoProducto.table_Producto.getSelectedRow();
            txt_PrecioCompra.setText(frmiCatalogoProducto.table_Producto.getValueAt(fila, 3).toString());
            txt_PrecioVenta.setText(frmiCatalogoProducto.table_Producto.getValueAt(fila, 4).toString());

            this.doDefaultCloseAction();
        }
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        this.doDefaultCloseAction();
        //this.dispose();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void cbo_TipoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_TipoCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_TipoCategoriaActionPerformed

    private void txt_StockIngresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_StockIngresoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_StockIngresoKeyTyped

    private void txt_StockIngresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_StockIngresoKeyReleased
        int actual, suma, ingreso, resta;

        seleccionar(txt_CodigoPro.getText());
        String registro = txt_StockIngreso.getText().replaceAll("[^0-9]", "");//admite caracters de 0 al 9 y lo demas remplaz por null
        if (!(registro.equals(""))) {

            switch (txt_StockIngreso.getText().charAt(0)) {
                case '-':
                    ingreso = Integer.parseInt(txt_StockIngreso.getText().replaceAll("[^0-9]", ""));
                    actual = Integer.parseInt(stock());
                    resta = actual - ingreso;
                    txt_Stock.setText(String.valueOf(resta));
                    break;
                case '+':
                    ingreso = Integer.parseInt(txt_StockIngreso.getText());
                    actual = Integer.parseInt(stock());
                    suma = actual + ingreso;
                    txt_Stock.setText(String.valueOf(suma));
                    break;
                default:
                    ingreso = Integer.parseInt(txt_StockIngreso.getText());
                    actual = Integer.parseInt(stock());
                    suma = actual + ingreso;
                    txt_Stock.setText(String.valueOf(suma));
                    break;
            }

        } else {
            txt_Stock.setText(stock());
        }
        /*NOTA -- para remplazar caracteres [^\\d.-] */

    }//GEN-LAST:event_txt_StockIngresoKeyReleased

    private void txt_NombreProKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreProKeyReleased
        txt_NombrePro.setText(txt_NombrePro.getText().toUpperCase());
    }//GEN-LAST:event_txt_NombreProKeyReleased

    private void txt_MarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MarcaKeyReleased
        txt_Marca.setText(txt_Marca.getText().toUpperCase());
    }//GEN-LAST:event_txt_MarcaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JComboBox<categoriaCont> cbo_TipoCategoria;
    private javax.swing.JComboBox<proveedoresCont> cbo_TipoProveedor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_CodigoPro;
    private javax.swing.JTextField txt_Marca;
    private javax.swing.JTextField txt_NombrePro;
    private javax.swing.JTextField txt_PrecioCompra;
    private javax.swing.JTextField txt_PrecioVenta;
    private javax.swing.JTextField txt_Stock;
    private javax.swing.JTextField txt_StockIngreso;
    // End of variables declaration//GEN-END:variables
}
